<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>snapmaster.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MainForm_old1.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="snapmaster.ico" />
    <None Remove="snapmaster_icon_24x24.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="snapmaster.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="snapmaster.ico" />
    <EmbeddedResource Include="snapmaster_icon_24x24.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>